### PR TITLE
Added ability to resize badge icons

### PR DESCRIPTION
**Pull request by knyto2**
This is a continuation PR of https://github.com/PolymerElements/paper-badge/pull/53, since that was closed due to inactivity. This new PR has all the code from the previous PR and correction to the typo.

### CODE REVIEW

**Comment by e111077** [comment]
Thanks for the submission, please run the formatter `npm run format` and sign the CLA, please!

**Comment by knyto2** [comment]
@googlebot I signed it!

**Comment by knyto2** [comment]
@googlebot I fixed it.

**Comment by knyto2** [comment]
Sorry, creating a new new branch and PR since I somehow have two separate committers.

**Pull request closed without merging**
