### PR TITLE
Fix closing paper-badge tag

### PR DESCRIPTION
**Pull request by saeidzebardast**

### CODE REVIEW

**Comment by notwaldorf** [comment]
@saeidzebardast Good catch, thanks! Would you mind also making the same change in `paper-badge.html`? The same typo is in the docs too 😊

**Comment by saeidzebardast** [comment]
@notwaldorf I've just fixed the same typo in paper-badge.html :wink:

**Comment by notwaldorf** [comment]
Thanks so much!!

**Comment by saeidzebardast** [comment]
You're welcome. Thank you for merging it :smiley:

**Pull request merged**
