### PR TITLE
Include iron-positioning. Fixes label position when using Shadow DOM.

### PR DESCRIPTION
**Pull request by MartinMoizard**
Fixes https://github.com/PolymerElements/paper-badge/issues/46.

### CODE REVIEW

**Comment by notwaldorf** [comment]
Hmm, I don't see why that change would fix anything. The element is using mixins, not classes, and it's already importing `iron-flex-layout` for that.

**Comment by notwaldorf** [comment]
Closing, since this PR doesn't really make any sense (or if it does, please re-open and explain what `iron-flex-layout` _class_ is actually being used.

**Comment by notwaldorf** [comment]
Ah, i understand why this works for the `hidden` case. It's because `iron-positioning` has
```
      [hidden] {
        display: none !important;
      }
```

Which is needed here: https://github.com/PolymerElements/paper-badge/blob/master/paper-badge.html#L107. I think it would be easier to just add that one style to `paper-badge` rather than all of them

I'm not sure why the positioning is fixed in the same way.

**Comment by MartinMoizard** [comment]
@notwaldorf : I created a new PR without including iron-positioning https://github.com/PolymerElements/paper-badge/pull/49

**Pull request closed without merging**
