### PR TITLE
allows to grow in width for labels with four or more characters

### PR DESCRIPTION
**Pull request by renfeng**
It helps to solve problems like this, https://github.com/PolymerEl/paper-tags/issues/28

### CODE REVIEW

**Comment by e111077** [comment]
This is technically a breaking change; it would also break a lot of visual diff tests. Perhaps have a flag / property that you can set that will set a class on the element so that it can conditionally switch to this behavior

**Comment by e111077** [comment]
Please reopen when requested changes are made

**Comment by renfeng** [comment]
What were the changes requested?

**Comment by e111077** [comment]
Can this feature be hidden behind a flag e.g.

```html
<style>
  .badge.grow { min-width: var(--paper-badge-width, 20px); }
  .badge.nogrow { width: var(--paper-badge-width, 20px); }
</style>
...
<div class$="badge [[__badgeClass(grow)]]">
...
<script>
Polymer({
  properties: { grow: { type: boolean, value: false }, ... }
  __badgeClass(shouldGrow) { return shouldGrow ? 'grow' : 'nogrow'; },
  ...
})
</script>
```

**Pull request closed without merging**
